name: CI

on: 
  push:
    branches:
      - main

jobs:
  buildd-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build docker image
      run: docker build -t celsoncampos/journey.api:latest .